Repository TBL-AIPal/AIPal, pull requests merged in 2025-04, with the labels that each got.

#82 Source Branch Restriction for Main
  .github/workflows/enforce-source-branch.yml
Labels: enhancement

#80 Add Image Context to Chunks
  packages/server/package.json
  packages/server/pnpm-lock.yaml
  packages/server/src/controllers/document.controller.js
  packages/server/src/services/RAG/embedding.service.js
  packages/server/src/services/RAG/preprocessing.py
  packages/server/src/services/document.service.js
  packages/server/src/utils/recursiveSplit.js
Labels: enhancement

#90 Merge DEV to PROD
  packages/server/package.json
  packages/server/pnpm-lock.yaml
  packages/server/src/controllers/document.controller.js
  packages/server/src/services/RAG/embedding.service.js
  packages/server/src/services/RAG/preprocessing.py
  packages/server/src/services/document.service.js
  packages/server/src/utils/recursiveSplit.js
Labels: enhancement

#78 Final mvp fixes
  package.json
  packages/client/next.config.js
  packages/client/src/app/auth/forgot-password/page.tsx
  packages/client/src/app/auth/login/page.tsx
  packages/client/src/app/auth/reset-password/page.tsx
  packages/client/src/app/auth/signup/page.tsx
  packages/client/src/app/courses/[courseId]/overview/_PageSections/AccountTable.tsx
  packages/client/src/app/courses/[courseId]/overview/_PageSections/UpdateCourseForm.tsx
  packages/client/src/app/courses/[courseId]/overview/page.tsx
  packages/client/src/app/courses/[courseId]/rooms/[roomId]/_PageSections/SettingsBar.tsx
  packages/client/src/app/courses/[courseId]/rooms/[roomId]/page.tsx
  packages/client/src/app/courses/[courseId]/rooms/page.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/RoomCreateForm.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/TemplateRow.tsx
  packages/client/src/app/dashboard/courses/_PageSections/APIKeyForm.tsx
  packages/client/src/app/dashboard/courses/_PageSections/CourseCreateForm.tsx
  packages/client/src/app/dashboard/courses/_PageSections/DescriptionForm.tsx
  packages/client/src/app/dashboard/courses/_PageSections/NameForm.tsx
  packages/client/src/lib/API/course/mutations.ts
  packages/client/src/lib/API/room/mutations.ts
  packages/client/src/lib/API/tutorialgroup/mutations.ts
  packages/client/src/lib/types/course.ts
  packages/client/src/lib/types/room.ts
  packages/server/src/config/roles.js
  packages/server/src/controllers/auth.controller.js
  packages/server/src/controllers/course.controller.js
  packages/server/src/controllers/tutorialGroup.controller.js
  packages/server/src/models/course.model.js
  packages/server/src/models/index.js
  packages/server/src/models/room.model.js
  packages/server/src/models/tutorial.group.model.js
  packages/server/src/routes/v1/course.route.js
  packages/server/src/services/course.service.js
  packages/server/src/services/email.service.js
  packages/server/src/services/index.js
  packages/server/src/services/message.service.js
  packages/server/src/services/tutorial.group.service.js
  packages/server/src/validations/course.validation.js
  packages/server/src/validations/room.validation.js
  packages/server/src/validations/tutorialGroup.validation.js
  packages/server/src/websockets/setupWebSocket.js
  scripts/pull-and-update-container.sh
Labels: enhancement

#93 Fix double import and use of wrong package
  package.json
  packages/client/src/app/courses/[courseId]/overview/page.tsx
  packages/client/src/app/courses/[courseId]/rooms/page.tsx
Labels: bug

#89 Fix Tests
  .husky/post-commit
  .husky/pre-commit
  .npmrc
  package.json
  packages/client/.husky/post-commit
  packages/client/.husky/pre-commit
  packages/client/.lintstagedrc.json
  packages/client/jest.config.js
  packages/client/jest.setup.js
  packages/client/package.json
  packages/client/src/__tests__/pages/HomePage.test.tsx
  packages/server/.husky/post-commit
  packages/server/.husky/pre-commit
  packages/server/.lintstagedrc.json
  packages/server/jest.config.js
  packages/server/package.json
  packages/server/pnpm-lock.yaml
  packages/server/src/controllers/course.controller.js
  packages/server/src/models/course.model.js
  packages/server/src/services/course.service.js
  packages/server/tests/fixtures/course.fixture.js
  packages/server/tests/fixtures/document.fixture.js
  packages/server/tests/fixtures/template.fixture.js
  packages/server/tests/fixtures/user.fixture.js
  packages/server/tests/integration/auth.test.js
  packages/server/tests/integration/course.test.js
  packages/server/tests/integration/document.test.js
  packages/server/tests/integration/user.test.js
  packages/server/tests/unit/models/course.model.test.js
  packages/server/tests/unit/models/document.model.test.js
  packages/server/tests/unit/models/template.model.test.js
  packages/server/tests/unit/models/user.model.test.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug

#101 Fix Dockerfile, improve Upload Materials, and UI
  packages/client/Dockerfile.development
  packages/client/Dockerfile.production
  packages/client/src/app/courses/[courseId]/materials/_PageSections/DocumentRow.tsx
  packages/client/src/app/courses/[courseId]/materials/_PageSections/DocumentTable.tsx
  packages/client/src/app/courses/[courseId]/materials/page.tsx
  packages/client/src/app/courses/[courseId]/rooms/[roomId]/_PageSections/MarkdownRenderer.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/AddConstraintButton.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/ConstraintForm.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/DocumentSelectionForm.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/DocumentStatusIndicator.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/TemplateCreateForm.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/TemplateForm.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/TemplateRow.tsx
  packages/client/src/app/courses/[courseId]/templates/_PageSections/TemplateTable.tsx
  packages/client/src/app/courses/[courseId]/templates/page.tsx
  packages/client/src/app/dashboard/courses/_PageSections/CourseGallery.tsx
  packages/client/src/app/dashboard/courses/page.tsx
  packages/client/src/app/layout.tsx
  packages/client/src/components/Icons.tsx
  packages/client/src/components/gallery/Gallery.tsx
  packages/client/src/components/ui/SelectableList.tsx
  packages/client/src/components/ui/Tag.tsx
  packages/client/src/lib/API/document/mutations.ts
  packages/client/src/lib/types/document.ts
  packages/client/src/lib/utils/error.ts
  packages/server/.dockerignore
  packages/server/Dockerfile.development
  packages/server/Dockerfile.production
  packages/server/src/controllers/document.controller.js
  packages/server/src/models/document.model.js
  packages/server/src/routes/v1/course.route.js
  packages/server/src/services/RAG/embedding.service.js
  packages/server/src/services/chunk.service.js
  packages/server/src/services/course.service.js
  packages/server/src/services/document.service.js
  packages/server/src/services/index.js
  packages/server/src/utils/LLMError.js
  packages/server/src/validations/document.validation.js
  packages/server/tests/fixtures/course.fixture.js
  packages/server/tests/integration/course.test.js
  packages/server/tests/integration/template.test.js
  pnpm-lock.yaml
Labels: bug, enhancement

#99 Bug fixes
  packages/client/src/app/courses/[courseId]/overview/page.tsx
  packages/client/src/app/courses/[courseId]/rooms/[roomId]/page.tsx
  packages/client/src/app/courses/[courseId]/rooms/page.tsx
  packages/client/src/app/dashboard/profile/page.tsx
  packages/client/src/lib/API/message/mutations.ts
  packages/client/src/lib/API/room/mutations.ts
  packages/client/src/lib/types/message.ts
  packages/client/src/lib/types/room.ts
  packages/server/src/config/roles.js
  packages/server/src/controllers/auth.controller.js
  packages/server/src/controllers/message.controller.js
  packages/server/src/controllers/tutorialGroup.controller.js
  packages/server/src/models/room.model.js
  packages/server/src/routes/v1/course.route.js
  packages/server/src/routes/v1/message.route.js
  packages/server/src/services/email.service.js
  packages/server/src/services/message.service.js
  packages/server/src/services/tutorial.group.service.js
  packages/server/src/validations/message.validation.js
  packages/server/src/validations/room.validation.js
Labels: bug
